#version 450

layout (local_size_x = 128, local_size_y = 1, local_size_z = 1) in;

layout (set = 0, binding = 0) buffer InputBuffer {
    int inBuffer[];
};
layout (set = 0, binding = 1) buffer OutputBuffer {
    int outBuffer[];
};

layout (set = 0, binding = 2) uniform InputUniform {
    int emitN;
};

uint global = 2;

void add_o(uint a) {
   global = global + a;
   return;
}

void main(void) {
    uint index = gl_GlobalInvocationID.x;
    add_o(index);
    int element = inBuffer[index];
    uint offset = index * uint(emitN);
    add_o(offset);
    outBuffer[index] = int(global);
}
