#version 450

layout (local_size_x = 128, local_size_y = 1, local_size_z = 1) in;

layout (set = 0, binding = 0) buffer InputBuffer {
    vec3 inBuffer[];
};
layout (set = 0, binding = 1) buffer OutputBuffer {
    vec4 outBuffer[];
};

uint global = 2;

void add_o(uint a) {
   global = global + a;
   return;
}

void main(void) {
    uint index = gl_GlobalInvocationID.x;
    add_o(index);
    vec3 element = inBuffer[index];
    add_o(index);
    outBuffer[global] = element.zxyz;
}
