#version 450

layout (local_size_x = 128, local_size_y = 1, local_size_z = 1) in;

layout (set = 0, binding = 0) buffer InputBuffer {
    int inBuffer[];
};
layout (set = 0, binding = 1) buffer OutputBuffer {
    bool outBuffer[];
};

layout (set = 0, binding = 2) uniform InputUniform {
    int filterValue;
};

void main(void) {
    uint index = gl_GlobalInvocationID.x;
    int element = inBuffer[index];
    outBuffer[index] = (element == filterValue);
}
