name: CI
on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: coursier/cache-action@v6
      - uses: coursier/setup-action@v1
        with:
          jvm: graalvm-java21
      - run: sbtn "formatCheckAll"